### ISSUE TITLE
项目Demo好像不大行，运行测量工具是就报错

### ISSUE THREAD

**Issue by zhou199604** [roomanl/ArcgisTool#10]
2020-04-12 08:28:53.182 7221-7221/cn.sddman.gis E/InputEventReceiver: Exception dispatching input event.
2020-04-12 08:28:53.182 7221-7221/cn.sddman.gis E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2020-04-12 08:28:53.187 7221-7221/cn.sddman.gis E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'com.esri.arcgisruntime.mapping.Viewpoint com.esri.arcgisruntime.mapping.ArcGISMap.getInitialViewpoint()' on a null object reference
        at cn.sddman.arcgistool.manager.ArcgisToolManager$1.onDown(ArcgisToolManager.java:98)
        at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.a(SourceFile:309)
        at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.a(SourceFile:273)
        at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.onTouch(SourceFile:248)
        at cn.sddman.arcgistool.manager.ArcgisToolManager$1.onTouch(ArcgisToolManager.java:113)
        at com.esri.arcgisruntime.mapping.view.MapView.onTouchEvent(SourceFile:864)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5303)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5103)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4671)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4637)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4777)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4645)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4834)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4671)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4637)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4645)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7346)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7315)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7276)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7452)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:250)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6821)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    	at com.android.
2020-04-12 08:28:53.188 7221-7221/cn.sddman.gis D/AndroidRuntime: Shutting down VM
2020-04-12 08:28:53.196 7221-7221/cn.sddman.gis E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.sddman.gis, PID: 7221
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.esri.arcgisruntime.mapping.Viewpoint com.esri.arcgisruntime.mapping.ArcGISMap.getInitialViewpoint()' on a null object reference
        at cn.sddman.arcgistool.manager.ArcgisToolManager$1.onDown(ArcgisToolManager.java:98)
        at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.a(SourceFile:309)
        at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.a(SourceFile:273)
        at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.onTouch(SourceFile:248)
        at cn.sddman.arcgistool.manager.ArcgisToolManager$1.onTouch(ArcgisToolManager.java:113)
        at com.esri.arcgisruntime.mapping.view.MapView.onTouchEvent(SourceFile:864)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5303)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5103)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4671)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4637)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4777)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4645)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4834)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4671)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4637)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4645)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7346)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7315)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7276)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7452)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:250)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6821)
        at java.lang.reflect.Method.invoke(Native Method)
2020-04-12 08:28:53.197 7221-7221/cn.sddman.gis E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by roomanl** [comment]
BUG已修复，也不算BUG，就是不小心把我测试代码提交上来了
